### ISSUE TITLE
Loading external libs (scripts) in a project

### ISSUE THREAD

**Issue by antonioOrtiz** [synapticism/wordpress-gulp-starter-kit#22]
I apologize  in advance if I missed something, however I am not following the TUT to install a typical `js` script.

This is my `gulpconfig.js` scripts section:
```
    scripts: {
    bundles: { // Bundles are defined by a name and an array of chunks to concatenate; warning: it's up to you to manage dependencies!
      core: ['core']
    , pg8: ['pg8', 'core']
    }
  , chunks: { // Chunks are arrays of globs matching source files that combine to provide specific functionality
      core: [
        src+'js/responsive-menu.js'
      , src+'js/core.js'
      ]
    , pg8: [
        modules+'fastclick/lib/fastclick.js'
      , modules+'html5-history-api/history.js'
      , modules+'spin.js/spin.js'
      , modules+'spin.js/jquery.spin.js'
      , modules+'wp-ajax-page-loader/wp-ajax-page-loader.js'
      , src+'js/page-loader.js'
      ]
    }
```

As you can see it is pretty intact from what you have created save for the following:

```
, pg8: [
        modules+'fastclick/lib/fastclick.js'
    
```
My first question is:
Is that the correct way you would add a lib/external script from the `node_modules` folder and your local 'js' folder (js folder in `src` dir) to get processed?

Could you explain explain the difference between `bundles, chunks and pg8`?  I found the section where you compared it to `browserify` but I am a tad confused. :)

Also running `gulp` in regards to script output, seems to spit out a js folder (in your child folder), which contains a minified and nonminified versions of your scripts; Is there a place when you're ready for PROD to just specify minified? Does that also occur for CSS?

Thank you in advance!

**Comment by synapticism** [comment]
Yes, that looks about right. You can verify this by running `gulp` and checking what you find in the `build` folder. Is `fastclick.js` at the top of the file? One caveat: you probably want to add this script to the `core` chunk since it's not actually related to the page loading functionality (which is coded `pg8` for brevity).

As for the second point, I apologize for this whole bundles and chunks thing; it seems to be unnecessarily confusing despite my intentions for it to be straight-forward way to flexibly load different scripts under different conditions. So, for example, you're likely to have a JS file loaded on every page to handle some things like what `fastclick` provides, but if you also have some JS for a contact form you'll probably want that in a separate file so you aren't loading it in places where you don't need it. 

Additionally, this bundles/chunks approach allows some level of user configurability *at the theme level*. If you look into the very basic theme included in this package you'll see some switches to allow the page loader script to be switched on and off. Behind the scenes, the theme is loading scripts based on conditionals *e.g.* if the page loading feature is switched on load `wp-pg8.js`. If not, `wp-core.js` gets loaded. From this you should see that your `fastclick.js` will go into the core bundle since you want it loaded regardless of whether the page loading script is on or off.

And by extension, if you have a contact form script or something all you need to do is write a conditional in the `assets.php` file to load `wp-contact.js` or whatever if the current page template equals `templates/contact-form.php` or however you set things up.

The basic idea here is that building many versions of scripts is easy since you're already using a build process. The usual WP way of doing things is to load 5 scripts for 5 features. With this approach you have many more than 5 scripts but only load the one that has the set of features you need. Your `js` folder ends up containing: `wp-a.js`, `wp-a-b.js` and `wp-b.js`. Then, in your theme, you can specify which features you want and then load only the one file that has the functionality you require. It's meant to form the basis for user-configurable option screens and such but I leave that up to you.

You can also scrap all that and just specify the scripts you need in one chunk and then load only that. No need to muck around with the added complexity if you only have one use case :)

As for minification, this is left up to the theme to load minified files or not. I have it setup so that you get unminified files in development and minified scripts in production. Sooner or later will move on to using source maps. CSS is a different matter; here you will get properly minified files in production with the `gulp dist` command.

Hope this answers your questions!
