### ISSUE TITLE
inclusion of method's styles and javascript in my Gulp task

### ISSUE THREAD

**Issue by BorisKamp** [synapticism/wordpress-gulp-starter-kit#52]
Hi guys! Im not sure if this section is meant for questions like this but I'm struggling with a question.
I want to include the following modules in my builds conditionally:

1. Bootstrap partials (differ per project)
2. ParsleyJS
3. Photoswipe

I've installed them all with npm install, now I wonder how I should inlcude them in my Gulp task. All modules have .(s)css and .js files I need to include. I see two options:

1. copy the files over from the node_modules folder to my own vendor folders for both js and stylesheets
2. import them dynamically in my Gulp tasks from the node_modules folder. This way I don't have to copy them over each time.

In my opinion #2 is the smartest, although Im not sure it's the best. I would like to get some insight on this from some more experienced Gulp developers. I'm not getting #2 to work (only partially) so was wondering if I should stop at all and go to #1, or continue.

Thanks guys!

**Comment by synapticism** [comment]
Sure, I welcome questions/discussion here and will reply when I have time to properly consider things. I'm not a ninja-level developer or anything tho so I welcome other comments as well :) 

I'm exclusively of a mind to import dependencies dynamically in some way (option 2) as that is one of the main advantages of working with npm etc. Now, when you say you want to include these modules conditionally do you mean that you want users of the theme to be able to activate/deactivate something like ParsleyJS? Or more like you want to use it in some projects but not others?

The way I personally handle different JS configs is by using the custom bundles/chunks system outlined in `gulpconfig.js`. If you're looking for a more standard approach you can try Webpack/Browserify but for most WP-based projects I've found them to be overkill. With the setup offered in this project Gulp will generate as many script bundles as you specify... and then it's up to the theme to load whichever bundle you want to use. It'll quickly get too complicated if you have many scripts you want to load conditionally... but with only a handful it should be alright. Like, you might have a script bundle that is just ParsleyJS, another that is only Photoswipe, and one that is ParsleyJS *and* Photoswipe. Or maybe you'll only want to load Photoswipe on singular content in which case it makes sense to isolate that in its own bundle. It's really up to you.

Conditionally loading Sass partials and CSS is more problematic. You can use maps within your Sass config file and a conditional function to load or not load specific mixins but I don't think you can conditionally import files (a limitation of Sass). But here too you can adopt a policy of generating many different CSS files and only loading what you need at runtime. And of course you might want to take ownership of the Sass partials that come with a project and integrate them more fully into your theme. JS lends itself well to modularity but I find that simply bolting third party CSS into a project often produces lousy results. It all depends how far you want to take it and what your design goals are. 

One thing I've wrestled with recently is the question of keeping three configuration spaces aligned... like there's a JavaScript configuration, a Sass configuration, and something that happens in PHP at the theme level. Keeping all of these parts working together is a real hassle... so nowadays I use a master configuration file that populates Sass and the theme. I've got it to the point where if I want to swap out a module I can flip true to false in a config file, run the build process all over again, and have a nice, clean theme with no extra fluff that does exactly what I want. If you'd like a sample of that check out the develop branch right now; there's a version in there where I showcase this workflow.

**Comment by synapticism** [comment]
Oh, and another small tool worth familiarizing yourself with is loadCSS: https://github.com/filamentgroup/loadCSS

You may find this handy with something like Photoswipe if you're only loading some CSS on singular pages and what-not. I use Magnific Popup in some of my theming projects and have it set to use jQuery to look for *more than one image* and only load the extra CSS if there's actually enough on the page for a lightbox gallery to work. But this is getting a little OCD 🗡

**Comment by BorisKamp** [comment]
Hi Synapticsm!

Thanks for your your thorough answer, I really appreciate it!

I indeed created three js files as output:
- my basic `app.js`
- my basic app.js combined with Photoswipe `appPhotowipe.js`
- my basic app.js combined with Parsley `appParlsey.js`

this works awesome, I conditionally load them in my functions.php depending on the pages where I need them.

for example, my `appPhotowipe.js` chunk looks like this:
```
appPhotoswipe: [
        modules+'photoswipe/dist/photoswipe.js',
        modules+'photoswipe/dist/photoswipe-ui-default.js',
        src+'js/photoswipe-custom.js'
      ],
```

is the the right way to include the files from the modules folder? In my opinion it is but would like to confirm.

about the stylesheets, I have two stylesheets `style.scss` and `style-photoswipe.scss`
style-photoswipe.scss just consists of the following:
```
//include the main .scss file as base
@import "style.scss";

//Add Photoswipe to the base and create new file
    @import "../../node_modules/photoswipe/src/css/_main-settings.scss";
    @import "../../node_modules/photoswipe/src/css/main.scss";
    @import "../../node_modules/photoswipe/src/css/default-skin/default-skin.scss";
```

again, is this the way to go for scss imports? just wondering.

about loadCSS, isn't it faster to just make one request with everything in one file? Or are you saying it's probably better to load Photoswipe with this tool after all the css/js is rendered?

great tip anyway, thanks!

**Comment by synapticism** [comment]
Sounds like you're on the right path, yes.

I think you should be able to skip `../../node_modules/` in your Sass when adding that stuff; check the load paths in `gulpconfig.js` as that should be there already. I've noticed path resolution doesn't always work the way you think it should so don't spend more than a few minutes on it if you already have something working :) 

Anyway, the main trade-offs to consider here are the number of requests, payload size, and caching. On one extreme you can put everything you could possibly need into one file but then it might be bloated and contain a lot of stuff that isn't necessary for most pages to work properly. On the other end you can modularize everything but then you're going to have many requests. And on some third axis you can conditionally combine things all over the place but then you won't be taking advantage of caching. The sweet spot is somewhere in the middle of all this and it's really dependent on your project... 

However in this case I would recommend lazy loading all the stuff you need for Photoswipe since users don't need immediate access to any of that anyhow. Keep your main styles in one file, generate a second CSS file just for Photoswipe, and load that with loadCSS called from your initialization script (`photoswipe-custom.js`). The extra request isn't going to cause a performance hit because it isn't done on load and you take advantage of caching the main CSS file anyhow so it basically cancels out.

**Comment by BorisKamp** [comment]
Thanks for the great reply again.

I was looking into skipping `../../node_modules/` but have no clue how to use the `modules` var from `gulpconfig.js` have no clue how to. Any ideas? I've got it working perfectly the way I described but am always looking for improvements.

Thanks about the explanation on the loading of files, I fully understand and agree that I should load the Photoswipe css independent from the main css by using lazy load.

Same is applicable to the javascript this plugin requires right? I've combined that with the main js but results in a way bigger filesize.

**Comment by synapticism** [comment]
Try leaving `../../node_modules/` out and see if it works; this is what `includePaths` in `gulpconfig.js` is meant to accomplish. Just `@import "photoswipe/src/css/main.scss";` and let me know how that goes.

The way I handle specialized functionality like a lightbox script is by bundling just the third party script and my custom activator script together and conditionally lazy load that (using the `defer` property) only where required (in my case, after passing the `is_singular()` test). This script, after loading, will scan the current post for images and lazy load CSS (using `loadCSS`, already bundled in a head script since I use it elsewhere)/activate itself if there are enough images on the page. (If you feel like poking around you can see this in action in [this theme](https://github.com/synapticism/pendrell) but you'll have to switch to the develop branch at the present time... and I warn ya, it's messy.)

Anyway, if all this seems too complicated don't worry about it... this is definitely premature optimization for most projects :) but in general if you've got specialized functionality that doesn't activate on page load I recommend conditionally lazy loading that stuff only when you need it.

**Comment by BorisKamp** [comment]
Using:
```
//Add Photoswipe to the base and create new file
    @import "photoswipe/src/css/_main-settings.scss";
    @import "photoswipe/src/css/main.scss";
    @import "photoswipe/src/css/default-skin/default-skin.scss";
```

works as well (-:. Although, I don't understand why it works, how can it 'know' Im looking in the `node_modules` folder?

Thanks for the basic walkthrough on the optimization, this is a little to much for me now, but it's good to know it exists!

one question about Browsersync. Isn't it meant to just 'inject' the styles and not refresh the whole page when I change a something and that file is watched?
right now the following happens:
- I make a change
- change get's injected and I see it.
- directly after the page refreshes and scrolls to the top again, this is really inconvenient.

Any ideas?

**Comment by synapticism** [comment]
It'll know because the modules directories are in the path. Have a look at `gulpconfig.js` and check out `includePaths` :)

I can't help you much with BrowserSync as I don't really use it myself... best you go read the docs and have a look at the options in `gulpconfig.js` which are entirely configurable.

I'm going to close this now so it's not coming up on the main issues list... pretty sure you can still comment if you like tho!
